name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

  - name: Cache go mod
    uses: actions/cache@v2
    with:
      path: |
        /go/pkg
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-

    - name: Build
      run: make build

    - name: Run Unit Test
      run: make test-coverage

    - name: Upload Coverage Report to CodeCov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: build/coverage.out
