name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o lxcfs-admission-webhook ./cmd/

    - name: Unit Test
      run: |
        export PROJECT_NAME=github.com/${GITHUB_REPOSITORY}
        export PKG_LIST=$(go list ${PROJECT_NAME}/...)
        go test -short -coverprofile coverage.out -covermode=atomic ${PKG_LIST}

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: coverage.out
